version: 2

jobs:

  build-test-deploy:
    docker:
      - image: circleci/node:12

    working_directory: ~/express-rest-biolerplate

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Combat Preparation
          command: |
            docker-compose up -d app
            docker-compose exec -d app yarn start

      - run:
          name: Compile Code
          command: docker-compose exec app yarn build

      - run:
          name: Code Quality
          command: docker-compose exec app yarn lint

      - run:
          name: Code Specification
          command: |
            docker-compose exec app yarn unit
            docker-compose exec app yarn _codecov --token=$CODECOV_TOKEN

      - run:
          name: E2E Specification
          command: |
            docker-compose exec app sh -c "sleep 10"
            docker-compose exec app yarn e2e

      - run:
          name: Deploy Application
          command: |
            case "${CIRCLE_BRANCH}" in
              "develop"|*"release"*|"master")
                case "$CIRCLE_BRANCH" in
                  "develop")
                    APP_NAME=nodeapiuser
                    DEPLOYMENT_ENVIRONMENT=dev
                    ;;
                  *"release"*)
                    APP_NAME=nodeapiuser
                    DEPLOYMENT_ENVIRONMENT=stage
                    ;;
                  "master")
                    APP_NAME=nodeapiuser
                    DEPLOYMENT_ENVIRONMENT=prod
                    ;;
                esac
                HEROKU_TOKEN=a5765996-89ce-427e-9cce-7804e4fd0251
                echo $HEROKU_TOKEN | docker login -u "abiedoank@gmail.com" --password-stdin registry.heroku.com
                docker build -f ./tools/$DEPLOYMENT_ENVIRONMENT.Dockerfile -t $APP_NAME .
                docker tag $APP_NAME registry.heroku.com/$APP_NAME/web
                docker push registry.heroku.com/$APP_NAME/web
                docker-compose exec -e HEROKU_API_KEY=$HEROKU_TOKEN app yarn _heroku container:release web -a $APP_NAME
                ;;
            esac

workflows:
  version: 2
  workflow:
    jobs:
      - build-test-deploy
